[build]
  command = "./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"
  publish = "target"

[build.environment]
  JAVA_VERSION = "21"
  M2_HOME = "/usr/share/maven"