#Windows spring.datasource.url=jdbc:oracle:thin:@c0po8p9s4vpki0c6_high?TNS_ADMIN=./src/main/resources/wallet
spring.datasource.url=jdbc:oracle:thin:@c0po8p9s4vpki0c6_high?TNS_ADMIN=/home/ubuntu/wallet
spring.datasource.username=ADMIN
spring.datasource.password= Prafful@571999
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# 1. Sets SameSite to None, allowing cross-site cookies.
server.servlet.session.cookie.same-site=None 

# 2. Sets Secure flag to true, mandatory when SameSite=None.
# This forces the cookie to only be sent over HTTPS.
server.servlet.session.cookie.secure=true
spring.jpa.open-in-view=false

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# App Properties
bezkoder.app.jwtSecret = ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs = 86400000